In [15]:
from keras.models import Sequential
from keras.layers import Dense,Activation,Flatten,Dropout
from keras.layers import Conv2D,MaxPooling2D

def load_cnn():
    
    model=Sequential()

    model.add(Conv2D(256,(3,3),input_shape=( 50, 50, 3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    #The first CNN layer followed by Relu and MaxPooling layers
    
    model.add(Dropout(0.5))
    
    model.add(Conv2D(128,(3,3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    #The second convolution layer followed by Relu and MaxPooling layers

    model.add(Dropout(0.5))
    
    model.add(Flatten())
    #Flatten layer to stack the output convolutions from second convolution layer
    model.add(Dense(64,activation='relu'))
    #Dense layer of 64 neurons
    model.add(Dense(4,activation='softmax'))
    #The Final layer with two outputs for two categories

    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    
    
    model.load_weights('Mango_v1.h5')
    
    return model

In [17]:
import cv2,os
import numpy as np

test_path='test1'

img_names=os.listdir(test_path)

model=load_cnn()

category={0:'grade 1',1:'grade 2',2: 'grade 2-S', 3: 'grade 3'}

for img_name in img_names:
    img_path=os.path.join(test_path,img_name)
    img=cv2.imread(img_path)
    gray = img
    #gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    resized=cv2.resize(gray,(50,50))
    print('shape',resized.shape)
    normalized=resized/255.0
    reshaped=np.reshape(normalized,(1,50,50,3))
    result=model.predict(reshaped)
    label=np.argmax(result,axis=1)[0]
    prob=np.max(result,axis=1)[0]
    prob=round(prob,2)*100
    
    img[:50,:]=[0,255,0]
    img=cv2.resize(img,(750,500))
    
    cv2.putText(img,str(category[label]),(10,40),cv2.FONT_HERSHEY_SIMPLEX,2,
                (255,255,255),2)
    
    cv2.putText(img,str(prob),(300,40),cv2.FONT_HERSHEY_SIMPLEX,2,
                (255,255,255),2)
    
    cv2.imshow('LIVE',img)
    cv2.waitKey(1000)
    
    print(result,label,prob),

shape (50, 50, 3)
[[3.2350114e-18 1.4468733e-07 2.5218508e-08 9.9999988e-01]] 3 100.0
shape (50, 50, 3)
[[8.0220238e-13 1.7730300e-06 3.3308303e-09 9.9999821e-01]] 3 100.0
shape (50, 50, 3)
[[2.1959268e-08 2.1841850e-04 9.9978119e-01 3.2297663e-07]] 2 100.0
shape (50, 50, 3)
[[1.5140407e-06 9.9999785e-01 9.2773043e-08 4.9172786e-07]] 1 100.0
shape (50, 50, 3)
[[8.0067283e-03 9.9196965e-01 2.3605333e-05 1.0852385e-08]] 1 99.00000095367432
shape (50, 50, 3)
[[9.8516023e-01 1.4839655e-02 1.3191410e-10 8.0905508e-08]] 0 99.00000095367432
shape (50, 50, 3)
[[9.6761596e-01 3.2382526e-02 1.2006658e-06 3.4035543e-07]] 0 97.00000286102295


In [18]:
img.shape

(500, 750, 3)