In [1]:
from keras.models import Sequential
from keras.layers import Dense,Activation,Flatten,Dropout
from keras.layers import Conv2D,MaxPooling2D

def load_cnn():
    
    model=Sequential()

    model.add(Conv2D(256,(3,3),input_shape=( 50, 50, 1)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    #The first CNN layer followed by Relu and MaxPooling layers
    
    model.add(Dropout(0.5))
    
    model.add(Conv2D(128,(3,3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    #The second convolution layer followed by Relu and MaxPooling layers

    model.add(Dropout(0.5))
    
    model.add(Flatten())
    #Flatten layer to stack the output convolutions from second convolution layer
    model.add(Dense(64,activation='relu'))
    #Dense layer of 64 neurons
    model.add(Dense(4,activation='softmax'))
    #The Final layer with two outputs for two categories

    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    
    #model.load_weights('kurundu&wathu_v1.h5')
    model.load_weights('Mango_v1.h5')
    
    return model

Using TensorFlow backend.


In [ ]:
import cv2,os
import numpy as np

test_path='test1'

#img_names=os.listdir(test_path)
source = cv2.VideoCapture(0)

model=load_cnn()

category={0:'grade 1',1:'grade 2',2: 'grade 2-S', 3: 'grade 3'}

#for img_name in img_names:
while(True):
    #img_path=os.path.join(test_path,img_name)
    #img=cv2.imread(img_path)
    ret,img = source.read()
    gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    resized=cv2.resize(gray,(50,50))
    print('shape',resized.shape)
    normalized=resized/255.0
    reshaped=np.reshape(normalized,(1,50,50,1))
    result=model.predict(reshaped)
    label=np.argmax(result,axis=1)[0]
    prob=np.max(result,axis=1)[0]
    prob=round(prob,2)*100
    
    img[:50,:]=[0,255,0]
    img=cv2.resize(img,(250,250))
    
    cv2.putText(img,str(category[label]),(10,40),cv2.FONT_HERSHEY_SIMPLEX,2,
                (255,255,255),2)
    
    cv2.putText(img,str(prob),(200,40),cv2.FONT_HERSHEY_SIMPLEX,2,
                (255,255,255),2)
    
    cv2.imshow('LIVE',img)
    cv2.waitKey(1)
    
    print(result,label,prob),

In [ ]:
img.shape

In [2]:
import urllib.request
import cv2,os
import numpy as np

test_path='test1'

# Replace the URL with your own IPwebcam shot.jpg IP:port
url= 'http://192.168.43.1:8080/shot.jpg'

model=load_cnn()

category={0:'grade 1',1:'grade 2',2: 'grade 2-S', 3: 'grade 3'}

#for img_name in img_names:
while(True):
    # Use urllib to get the image from the IP camera
    imgResp = urllib.request.urlopen(url)

    # Numpy to convert into a array
    imgNp = np.array(bytearray(imgResp.read()),dtype=np.uint8)

    # Decode the array to OpenCV usable format
    img = cv2.imdecode(imgNp,-1)
    gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    resized=cv2.resize(gray,(50,50))
    print('shape',resized.shape)
    normalized=resized/255.0
    reshaped=np.reshape(normalized,(1,50,50,1))
    result=model.predict(reshaped)
    label=np.argmax(result,axis=1)[0]
    prob=np.max(result,axis=1)[0]
    prob=round(prob,2)*100
    
    img[:50,:]=[0,255,0]
    img=cv2.resize(img,(250,250))
    
    cv2.putText(img,str(category[label]),(10,40),cv2.FONT_HERSHEY_SIMPLEX,2,
                (255,255,255),2)
    
    cv2.putText(img,str(prob),(200,40),cv2.FONT_HERSHEY_SIMPLEX,2,
                (255,255,255),2)
    
    cv2.imshow('LIVE',img)
    cv2.waitKey(1)
    
    print(result,label,prob),

shape (50, 50)
[[2.7242434e-04 9.9972755e-01]] 1 100.0
shape (50, 50)
[[2.752088e-04 9.997248e-01]] 1 100.0
shape (50, 50)
[[2.7473454e-04 9.9972528e-01]] 1 100.0
shape (50, 50)
[[2.7625664e-04 9.9972373e-01]] 1 100.0
shape (50, 50)
[[2.7397988e-04 9.9972600e-01]] 1 100.0
shape (50, 50)
[[2.7244433e-04 9.9972755e-01]] 1 100.0
shape (50, 50)
[[2.7458425e-04 9.9972540e-01]] 1 100.0
shape (50, 50)
[[2.7593155e-04 9.9972409e-01]] 1 100.0
shape (50, 50)
[[2.7300519e-04 9.9972695e-01]] 1 100.0
shape (50, 50)
[[2.7322862e-04 9.9972671e-01]] 1 100.0
shape (50, 50)
[[2.7196345e-04 9.9972802e-01]] 1 100.0
shape (50, 50)
[[2.7175792e-04 9.9972826e-01]] 1 100.0
shape (50, 50)
[[2.7047863e-04 9.9972945e-01]] 1 100.0
shape (50, 50)
[[2.6959326e-04 9.9973041e-01]] 1 100.0
shape (50, 50)
[[2.6761217e-04 9.9973243e-01]] 1 100.0
shape (50, 50)
[[2.6740044e-04 9.9973255e-01]] 1 100.0
shape (50, 50)
[[2.660278e-04 9.997340e-01]] 1 100.0
shape (50, 50)
[[2.6137067e-04 9.9973863e-01]] 1 100.0
shape (50, 50)

[[4.6712541e-04 9.9953294e-01]] 1 100.0
shape (50, 50)
[[0.99208903 0.007911  ]] 0 99.00000095367432
shape (50, 50)
[[0.9988482  0.00115183]] 0 100.0
shape (50, 50)
[[0.99532    0.00467998]] 0 100.0
shape (50, 50)
[[0.9391359  0.06086411]] 0 93.99999976158142
shape (50, 50)
[[0.49134445 0.5086556 ]] 1 50.999999046325684
shape (50, 50)
[[0.03061619 0.9693838 ]] 1 97.00000286102295
shape (50, 50)
[[0.00143105 0.9985689 ]] 1 100.0
shape (50, 50)
[[1.5519901e-04 9.9984479e-01]] 1 100.0
shape (50, 50)
[[7.4649564e-05 9.9992537e-01]] 1 100.0
shape (50, 50)
[[4.0038163e-04 9.9959964e-01]] 1 100.0
shape (50, 50)
[[0.00174254 0.99825746]] 1 100.0
shape (50, 50)
[[9.121360e-04 9.990878e-01]] 1 100.0
shape (50, 50)
[[5.1494554e-04 9.9948502e-01]] 1 100.0
shape (50, 50)
[[1.6637698e-04 9.9983358e-01]] 1 100.0
shape (50, 50)
[[2.3319476e-04 9.9976677e-01]] 1 100.0
shape (50, 50)
[[6.7776455e-05 9.9993217e-01]] 1 100.0
shape (50, 50)
[[4.7516329e-05 9.9995244e-01]] 1 100.0
shape (50, 50)
[[2.3544531

shape (50, 50)
[[0.94818866 0.05181137]] 0 94.9999988079071
shape (50, 50)
[[0.9079213  0.09207874]] 0 91.00000262260437
shape (50, 50)
[[0.8810026  0.11899739]] 0 87.99999952316284
shape (50, 50)
[[0.5464656  0.45353448]] 0 55.000001192092896
shape (50, 50)
[[0.9813415  0.01865855]] 0 98.00000190734863
shape (50, 50)
[[0.9989967  0.00100328]] 0 100.0
shape (50, 50)
[[9.9956006e-01 4.3990620e-04]] 0 100.0
shape (50, 50)
[[9.9995196e-01 4.8087328e-05]] 0 100.0
shape (50, 50)
[[9.9997568e-01 2.4361498e-05]] 0 100.0
shape (50, 50)
[[9.9995387e-01 4.6122070e-05]] 0 100.0
shape (50, 50)
[[9.9997199e-01 2.7971382e-05]] 0 100.0
shape (50, 50)
[[9.999366e-01 6.341899e-05]] 0 100.0
shape (50, 50)
[[9.9994826e-01 5.1772440e-05]] 0 100.0
shape (50, 50)
[[9.9990189e-01 9.8063305e-05]] 0 100.0
shape (50, 50)
[[9.9995553e-01 4.4442208e-05]] 0 100.0
shape (50, 50)
[[9.9986589e-01 1.3413347e-04]] 0 100.0
shape (50, 50)
[[9.999995e-01 4.917761e-07]] 0 100.0
shape (50, 50)
[[1.00000e+00 1.68549e-08]] 0 

shape (50, 50)
[[3.430718e-04 9.996569e-01]] 1 100.0
shape (50, 50)
[[3.2895978e-04 9.9967110e-01]] 1 100.0
shape (50, 50)
[[2.8851538e-04 9.9971145e-01]] 1 100.0
shape (50, 50)
[[2.8044457e-04 9.9971956e-01]] 1 100.0
shape (50, 50)
[[3.1704237e-04 9.9968302e-01]] 1 100.0
shape (50, 50)
[[2.8055743e-04 9.9971944e-01]] 1 100.0
shape (50, 50)
[[2.7455596e-04 9.9972540e-01]] 1 100.0
shape (50, 50)
[[2.7734341e-04 9.9972266e-01]] 1 100.0
shape (50, 50)
[[1.9841261e-04 9.9980158e-01]] 1 100.0
shape (50, 50)
[[1.7484851e-04 9.9982518e-01]] 1 100.0
shape (50, 50)
[[1.5551514e-04 9.9984443e-01]] 1 100.0
shape (50, 50)
[[1.766988e-04 9.998233e-01]] 1 100.0
shape (50, 50)
[[1.608006e-04 9.998392e-01]] 1 100.0
shape (50, 50)
[[1.9652564e-04 9.9980348e-01]] 1 100.0
shape (50, 50)
[[2.1605835e-04 9.9978393e-01]] 1 100.0
shape (50, 50)
[[2.2544837e-04 9.9977452e-01]] 1 100.0
shape (50, 50)
[[9.999218e-01 7.819703e-05]] 0 100.0
shape (50, 50)
[[9.997013e-01 2.986003e-04]] 0 100.0
shape (50, 50)
[[9.9

[[1.0000000e+00 1.2507348e-09]] 0 100.0
shape (50, 50)
[[1.0000000e+00 3.8599465e-10]] 0 100.0
shape (50, 50)
[[1.000000e+00 8.876023e-11]] 0 100.0
shape (50, 50)
[[1.0000000e+00 2.2848617e-11]] 0 100.0
shape (50, 50)
[[1.000000e+00 7.702372e-12]] 0 100.0
shape (50, 50)
[[1.000000e+00 4.211449e-12]] 0 100.0
shape (50, 50)
[[1.0000000e+00 1.5608732e-12]] 0 100.0
shape (50, 50)
[[1.0000000e+00 1.0420329e-12]] 0 100.0
shape (50, 50)
[[1.000000e+00 5.549959e-12]] 0 100.0
shape (50, 50)
[[1.0000000e+00 2.3156388e-11]] 0 100.0
shape (50, 50)
[[1.0000000e+00 1.0675084e-10]] 0 100.0
shape (50, 50)
[[1.000000e+00 3.077657e-11]] 0 100.0
shape (50, 50)
[[1.0000000e+00 2.9164077e-11]] 0 100.0
shape (50, 50)
[[1.000000e+00 3.016029e-11]] 0 100.0
shape (50, 50)
[[1.000000e+00 9.977392e-11]] 0 100.0
shape (50, 50)
[[1.0000000e+00 1.4633014e-08]] 0 100.0
shape (50, 50)
[[0.00539584 0.9946042 ]] 1 99.00000095367432
shape (50, 50)
[[1.5654574e-04 9.9984348e-01]] 1 100.0
shape (50, 50)
[[1.1505970e-04 9.

[[0.9220014 0.0779985]] 0 92.00000166893005
shape (50, 50)
[[0.9039803 0.0960197]] 0 89.99999761581421
shape (50, 50)
[[0.9161404  0.08385963]] 0 92.00000166893005
shape (50, 50)
[[0.92743677 0.07256322]] 0 93.00000071525574
shape (50, 50)
[[0.8580376 0.1419624]] 0 86.00000143051147
shape (50, 50)
[[0.8764736  0.12352644]] 0 87.99999952316284
shape (50, 50)
[[0.80401826 0.19598173]] 0 80.0000011920929
shape (50, 50)
[[0.7381818  0.26181823]] 0 74.00000095367432
shape (50, 50)
[[0.7764226  0.22357745]] 0 77.99999713897705
shape (50, 50)
[[0.8255922  0.17440781]] 0 82.99999833106995
shape (50, 50)
[[0.8006607  0.19933932]] 0 80.0000011920929
shape (50, 50)
[[0.8755538  0.12444626]] 0 87.99999952316284
shape (50, 50)
[[0.8216666  0.17833339]] 0 81.99999928474426
shape (50, 50)
[[0.8155566 0.1844434]] 0 81.99999928474426
shape (50, 50)
[[0.6564105  0.34358948]] 0 66.00000262260437
shape (50, 50)
[[0.49919468 0.5008054 ]] 1 50.0
shape (50, 50)
[[0.69696534 0.30303466]] 0 69.9999988079071
sh

shape (50, 50)
[[0.3010513 0.6989487]] 1 69.9999988079071
shape (50, 50)
[[0.14535679 0.8546432 ]] 1 85.00000238418579
shape (50, 50)
[[0.16470353 0.8352965 ]] 1 83.99999737739563
shape (50, 50)
[[0.19115408 0.8088459 ]] 1 81.00000023841858
shape (50, 50)
[[0.23699772 0.7630023 ]] 1 75.99999904632568
shape (50, 50)
[[0.07490593 0.92509407]] 1 93.00000071525574
shape (50, 50)
[[0.07428894 0.9257111 ]] 1 93.00000071525574
shape (50, 50)
[[0.0189027  0.98109734]] 1 98.00000190734863
shape (50, 50)
[[0.00905459 0.99094546]] 1 99.00000095367432
shape (50, 50)
[[0.02874363 0.9712564 ]] 1 97.00000286102295
shape (50, 50)
[[0.01017645 0.9898235 ]] 1 99.00000095367432
shape (50, 50)
[[0.0105485  0.98945147]] 1 99.00000095367432
shape (50, 50)
[[0.00722098 0.99277896]] 1 99.00000095367432
shape (50, 50)
[[0.00785437 0.9921456 ]] 1 99.00000095367432
shape (50, 50)
[[0.01438985 0.9856102 ]] 1 99.00000095367432
shape (50, 50)
[[0.01208255 0.9879175 ]] 1 99.00000095367432
shape (50, 50)
[[0.01643666

shape (50, 50)
[[0.00792582 0.99207413]] 1 99.00000095367432
shape (50, 50)
[[0.00683757 0.9931624 ]] 1 99.00000095367432
shape (50, 50)
[[0.01565497 0.984345  ]] 1 98.00000190734863
shape (50, 50)
[[0.1429296 0.8570704]] 1 86.00000143051147
shape (50, 50)
[[9.9975818e-01 2.4183269e-04]] 0 100.0
shape (50, 50)
[[9.999957e-01 4.347073e-06]] 0 100.0
shape (50, 50)
[[9.991499e-01 8.500690e-04]] 0 100.0
shape (50, 50)
[[9.9992180e-01 7.8250225e-05]] 0 100.0
shape (50, 50)
[[0.95657927 0.04342077]] 0 95.99999785423279
shape (50, 50)
[[0.00173962 0.99826044]] 1 100.0
shape (50, 50)
[[5.1294570e-05 9.9994874e-01]] 1 100.0
shape (50, 50)
[[4.8870363e-05 9.9995112e-01]] 1 100.0
shape (50, 50)
[[5.074958e-05 9.999492e-01]] 1 100.0
shape (50, 50)
[[7.8430334e-05 9.9992156e-01]] 1 100.0
shape (50, 50)
[[2.9542035e-04 9.9970454e-01]] 1 100.0
shape (50, 50)
[[0.9907438  0.00925624]] 0 99.00000095367432
shape (50, 50)
[[9.9983776e-01 1.6223690e-04]] 0 100.0
shape (50, 50)
[[9.9998283e-01 1.7202299e-0

[[0.6161704  0.38382956]] 0 62.00000047683716
shape (50, 50)
[[0.5890014  0.41099858]] 0 58.99999737739563
shape (50, 50)
[[0.53241396 0.46758607]] 0 52.99999713897705
shape (50, 50)
[[0.42299157 0.5770084 ]] 1 57.999998331069946
shape (50, 50)
[[0.41752067 0.5824793 ]] 1 57.999998331069946
shape (50, 50)
[[0.41359085 0.5864092 ]] 1 58.99999737739563
shape (50, 50)
[[0.47595045 0.5240496 ]] 1 51.99999809265137
shape (50, 50)
[[0.46403027 0.53596973]] 1 54.00000214576721
shape (50, 50)
[[0.53796935 0.46203062]] 0 54.00000214576721
shape (50, 50)
[[0.5440875 0.4559125]] 0 54.00000214576721
shape (50, 50)
[[0.5375013  0.46249872]] 0 54.00000214576721
shape (50, 50)
[[0.6089547 0.3910453]] 0 61.000001430511475
shape (50, 50)
[[0.67945653 0.32054347]] 0 68.00000071525574
shape (50, 50)
[[0.57835543 0.42164454]] 0 57.999998331069946
shape (50, 50)
[[0.57270795 0.42729208]] 0 56.99999928474426
shape (50, 50)
[[0.56596273 0.43403727]] 0 56.99999928474426
shape (50, 50)
[[0.5136521  0.48634794]

[[0.99274534 0.0072546 ]] 0 99.00000095367432
shape (50, 50)
[[0.5223247  0.47767532]] 0 51.99999809265137
shape (50, 50)
[[0.3986371 0.6013629]] 1 60.00000238418579
shape (50, 50)
[[0.83519346 0.16480651]] 0 83.99999737739563
shape (50, 50)
[[0.94385344 0.05614656]] 0 93.99999976158142
shape (50, 50)
[[9.9988592e-01 1.1408039e-04]] 0 100.0
shape (50, 50)
[[9.9902868e-01 9.7133184e-04]] 0 100.0
shape (50, 50)
[[0.99717915 0.00282087]] 0 100.0
shape (50, 50)
[[0.9964361  0.00356389]] 0 100.0
shape (50, 50)
[[9.990144e-01 9.856359e-04]] 0 100.0
shape (50, 50)
[[9.9952412e-01 4.7595098e-04]] 0 100.0
shape (50, 50)
[[9.9998689e-01 1.3091577e-05]] 0 100.0
shape (50, 50)
[[9.999993e-01 7.118721e-07]] 0 100.0
shape (50, 50)
[[9.999993e-01 7.421794e-07]] 0 100.0
shape (50, 50)
[[9.9999571e-01 4.2430656e-06]] 0 100.0
shape (50, 50)
[[9.9997318e-01 2.6847156e-05]] 0 100.0
shape (50, 50)
[[0.9966029  0.00339713]] 0 100.0
shape (50, 50)
[[0.11910978 0.8808902 ]] 1 87.99999952316284
shape (50, 50)


shape (50, 50)
[[0.00852425 0.9914758 ]] 1 99.00000095367432
shape (50, 50)
[[0.00260885 0.9973911 ]] 1 100.0
shape (50, 50)
[[0.00267231 0.9973277 ]] 1 100.0
shape (50, 50)
[[0.00222071 0.9977793 ]] 1 100.0
shape (50, 50)
[[7.257199e-05 9.999274e-01]] 1 100.0
shape (50, 50)
[[7.003887e-05 9.999299e-01]] 1 100.0
shape (50, 50)
[[0.01680464 0.98319536]] 1 98.00000190734863
shape (50, 50)
[[0.03068063 0.96931934]] 1 97.00000286102295
shape (50, 50)
[[0.00205528 0.9979448 ]] 1 100.0
shape (50, 50)
[[5.3737167e-04 9.9946266e-01]] 1 100.0
shape (50, 50)
[[3.920403e-04 9.996080e-01]] 1 100.0
shape (50, 50)
[[0.01680453 0.9831955 ]] 1 98.00000190734863
shape (50, 50)
[[0.00323189 0.9967681 ]] 1 100.0
shape (50, 50)
[[0.00248582 0.9975141 ]] 1 100.0
shape (50, 50)
[[0.00136432 0.9986357 ]] 1 100.0
shape (50, 50)
[[2.583668e-04 9.997416e-01]] 1 100.0
shape (50, 50)
[[6.5500608e-05 9.9993455e-01]] 1 100.0
shape (50, 50)
[[6.9451856e-04 9.9930549e-01]] 1 100.0
shape (50, 50)
[[0.05964505 0.940355

[[0.8973216  0.10267845]] 0 89.99999761581421
shape (50, 50)
[[0.92004895 0.07995106]] 0 92.00000166893005
shape (50, 50)
[[0.94611037 0.05388965]] 0 94.9999988079071
shape (50, 50)
[[0.8352783  0.16472173]] 0 83.99999737739563
shape (50, 50)
[[0.9045684  0.09543164]] 0 89.99999761581421
shape (50, 50)
[[9.999993e-01 7.171113e-07]] 0 100.0
shape (50, 50)
[[9.9999607e-01 3.9137235e-06]] 0 100.0
shape (50, 50)
[[0.8252996 0.1747003]] 0 82.99999833106995
shape (50, 50)
[[0.99823916 0.00176087]] 0 100.0
shape (50, 50)
[[0.9977525  0.00224747]] 0 100.0
shape (50, 50)
[[0.9916694  0.00833059]] 0 99.00000095367432
shape (50, 50)
[[0.98930174 0.01069825]] 0 99.00000095367432
shape (50, 50)
[[0.9884432  0.01155681]] 0 99.00000095367432
shape (50, 50)
[[0.98711246 0.01288749]] 0 99.00000095367432
shape (50, 50)
[[0.9876357  0.01236429]] 0 99.00000095367432
shape (50, 50)
[[0.9904004  0.00959958]] 0 99.00000095367432
shape (50, 50)
[[0.98734224 0.01265773]] 0 99.00000095367432
shape (50, 50)
[[0.

[[0.9843286  0.01567139]] 0 98.00000190734863
shape (50, 50)
[[0.9213796  0.07862034]] 0 92.00000166893005
shape (50, 50)
[[0.95370436 0.04629565]] 0 94.9999988079071
shape (50, 50)
[[0.9574168  0.04258325]] 0 95.99999785423279
shape (50, 50)
[[0.9776248  0.02237525]] 0 98.00000190734863
shape (50, 50)
[[0.9905482  0.00945178]] 0 99.00000095367432
shape (50, 50)
[[0.99400204 0.00599789]] 0 99.00000095367432
shape (50, 50)
[[0.9986084  0.00139158]] 0 100.0
shape (50, 50)
[[0.99778605 0.00221397]] 0 100.0
shape (50, 50)
[[0.99796 0.00204]] 0 100.0
shape (50, 50)
[[0.9948586  0.00514139]] 0 99.00000095367432
shape (50, 50)
[[0.9955395 0.0044605]] 0 100.0
shape (50, 50)
[[0.99501884 0.00498114]] 0 100.0
shape (50, 50)
[[0.99666446 0.00333546]] 0 100.0
shape (50, 50)
[[0.9973992  0.00260082]] 0 100.0
shape (50, 50)
[[0.9977189  0.00228113]] 0 100.0
shape (50, 50)
[[0.9980021  0.00199792]] 0 100.0
shape (50, 50)
[[0.99855036 0.00144964]] 0 100.0
shape (50, 50)
[[0.9984864  0.00151351]] 0 100

shape (50, 50)
[[0.04480703 0.955193  ]] 1 95.99999785423279
shape (50, 50)
[[0.40375537 0.59624463]] 1 60.00000238418579
shape (50, 50)
[[0.41230235 0.5876976 ]] 1 58.99999737739563
shape (50, 50)
[[0.25879762 0.74120235]] 1 74.00000095367432
shape (50, 50)
[[0.59540814 0.4045919 ]] 0 60.00000238418579
shape (50, 50)
[[0.84976447 0.15023553]] 0 85.00000238418579
shape (50, 50)
[[0.7343517 0.2656483]] 0 73.00000190734863
shape (50, 50)
[[0.5034409  0.49655908]] 0 50.0
shape (50, 50)
[[0.8989325  0.10106745]] 0 89.99999761581421
shape (50, 50)
[[9.9999976e-01 2.6885712e-07]] 0 100.0
shape (50, 50)
[[9.9999976e-01 2.4820559e-07]] 0 100.0
shape (50, 50)
[[9.9999940e-01 6.2156886e-07]] 0 100.0
shape (50, 50)
[[9.9999988e-01 1.2784892e-07]] 0 100.0
shape (50, 50)
[[1.0000000e+00 3.6411947e-09]] 0 100.0
shape (50, 50)
[[9.999994e-01 5.419352e-07]] 0 100.0
shape (50, 50)
[[9.9999869e-01 1.2860921e-06]] 0 100.0
shape (50, 50)
[[0.9861281  0.01387186]] 0 99.00000095367432
shape (50, 50)
[[0.502

[[1.000000e+00 6.001154e-12]] 0 100.0
shape (50, 50)
[[1.0000000e+00 6.6495295e-12]] 0 100.0
shape (50, 50)
[[1.0000000e+00 1.1019678e-11]] 0 100.0
shape (50, 50)
[[1.0000000e+00 4.2806772e-11]] 0 100.0
shape (50, 50)
[[1.0000000e+00 1.3956675e-10]] 0 100.0
shape (50, 50)
[[1.0000000e+00 2.8814963e-11]] 0 100.0
shape (50, 50)
[[1.00000000e+00 1.07280726e-10]] 0 100.0
shape (50, 50)
[[1.0000000e+00 1.0560641e-10]] 0 100.0
shape (50, 50)
[[1.0000000e+00 1.9142411e-10]] 0 100.0
shape (50, 50)
[[1.0000000e+00 1.6018079e-10]] 0 100.0
shape (50, 50)
[[1.00000000e+00 1.03918776e-10]] 0 100.0
shape (50, 50)
[[1.000000e+00 5.161043e-10]] 0 100.0
shape (50, 50)
[[1.000000e+00 5.728827e-10]] 0 100.0
shape (50, 50)
[[1.000000e+00 8.543761e-10]] 0 100.0
shape (50, 50)
[[1.0000000e+00 4.4394677e-10]] 0 100.0
shape (50, 50)
[[1.0000000e+00 3.2565817e-10]] 0 100.0
shape (50, 50)
[[1.000000e+00 9.160385e-10]] 0 100.0
shape (50, 50)
[[1.0000000e+00 3.1133726e-10]] 0 100.0
shape (50, 50)
[[1.0000000e+00 

[[0.48388058 0.5161194 ]] 1 51.99999809265137
shape (50, 50)
[[0.64960694 0.3503931 ]] 0 64.99999761581421
shape (50, 50)
[[0.6109017  0.38909826]] 0 61.000001430511475
shape (50, 50)
[[0.57614064 0.4238594 ]] 0 57.999998331069946
shape (50, 50)
[[0.4900975 0.5099025]] 1 50.999999046325684
shape (50, 50)
[[0.7158058 0.2841942]] 0 72.00000286102295
shape (50, 50)
[[0.66066647 0.33933356]] 0 66.00000262260437
shape (50, 50)
[[0.68961877 0.3103812 ]] 0 68.99999976158142
shape (50, 50)
[[0.75744134 0.24255875]] 0 75.99999904632568
shape (50, 50)
[[0.6777728  0.32222715]] 0 68.00000071525574
shape (50, 50)
[[0.6937571  0.30624285]] 0 68.99999976158142
shape (50, 50)
[[0.6434531  0.35654682]] 0 63.999998569488525
shape (50, 50)
[[0.82964814 0.17035186]] 0 82.99999833106995
shape (50, 50)
[[0.7412659 0.2587341]] 0 74.00000095367432
shape (50, 50)
[[0.8234932  0.17650683]] 0 81.99999928474426
shape (50, 50)
[[0.7305226 0.2694774]] 0 73.00000190734863
shape (50, 50)
[[0.4924542  0.50754577]] 1 

shape (50, 50)
[[0.9851425  0.01485742]] 0 99.00000095367432
shape (50, 50)
[[9.9935287e-01 6.4709503e-04]] 0 100.0
shape (50, 50)
[[0.9989973  0.00100277]] 0 100.0
shape (50, 50)
[[1.3502882e-04 9.9986494e-01]] 1 100.0
shape (50, 50)
[[6.121914e-06 9.999939e-01]] 1 100.0
shape (50, 50)
[[4.1065250e-06 9.9999595e-01]] 1 100.0
shape (50, 50)
[[2.4323992e-06 9.9999762e-01]] 1 100.0
shape (50, 50)
[[1.3406559e-06 9.9999869e-01]] 1 100.0
shape (50, 50)
[[3.3376668e-06 9.9999666e-01]] 1 100.0
shape (50, 50)
[[3.6858019e-06 9.9999630e-01]] 1 100.0
shape (50, 50)
[[3.2983446e-06 9.9999666e-01]] 1 100.0
shape (50, 50)
[[3.6094316e-06 9.9999642e-01]] 1 100.0
shape (50, 50)
[[4.4626427e-06 9.9999559e-01]] 1 100.0
shape (50, 50)
[[5.043396e-06 9.999950e-01]] 1 100.0
shape (50, 50)
[[6.084396e-06 9.999939e-01]] 1 100.0
shape (50, 50)
[[7.7718050e-06 9.9999225e-01]] 1 100.0
shape (50, 50)
[[1.3736566e-05 9.9998629e-01]] 1 100.0
shape (50, 50)
[[2.4158506e-05 9.9997580e-01]] 1 100.0
shape (50, 50)
[

[[0.95192003 0.04807993]] 0 94.9999988079071
shape (50, 50)
[[0.930711   0.06928899]] 0 93.00000071525574
shape (50, 50)
[[0.9250078  0.07499216]] 0 93.00000071525574
shape (50, 50)
[[0.8751322 0.1248678]] 0 87.99999952316284
shape (50, 50)
[[0.7879342 0.2120658]] 0 79.00000214576721
shape (50, 50)
[[0.80579704 0.194203  ]] 0 81.00000023841858
shape (50, 50)
[[0.7408443  0.25915578]] 0 74.00000095367432
shape (50, 50)
[[0.7659128  0.23408729]] 0 76.99999809265137
shape (50, 50)
[[0.8152566  0.18474337]] 0 81.99999928474426
shape (50, 50)
[[0.87283987 0.12716012]] 0 87.00000047683716
shape (50, 50)
[[0.85491157 0.1450884 ]] 0 85.00000238418579
shape (50, 50)
[[0.819873   0.18012701]] 0 81.99999928474426
shape (50, 50)
[[0.77915716 0.22084281]] 0 77.99999713897705
shape (50, 50)
[[0.765283   0.23471701]] 0 76.99999809265137
shape (50, 50)
[[0.7957282  0.20427176]] 0 80.0000011920929
shape (50, 50)
[[0.7239585  0.27604148]] 0 72.00000286102295
shape (50, 50)
[[0.86670053 0.13329946]] 0 87

shape (50, 50)
[[0.9448265  0.05517345]] 0 93.99999976158142
shape (50, 50)
[[0.9756988  0.02430115]] 0 98.00000190734863
shape (50, 50)
[[0.9727486 0.0272514]] 0 97.00000286102295
shape (50, 50)
[[0.9564486  0.04355142]] 0 95.99999785423279
shape (50, 50)
[[0.9441407  0.05585932]] 0 93.99999976158142
shape (50, 50)
[[0.917627   0.08237307]] 0 92.00000166893005
shape (50, 50)
[[0.95218027 0.04781973]] 0 94.9999988079071
shape (50, 50)
[[0.9617325  0.03826749]] 0 95.99999785423279
shape (50, 50)
[[0.9811606  0.01883938]] 0 98.00000190734863
shape (50, 50)
[[0.97789246 0.02210748]] 0 98.00000190734863
shape (50, 50)
[[0.9584828  0.04151718]] 0 95.99999785423279
shape (50, 50)
[[0.87836194 0.12163801]] 0 87.99999952316284
shape (50, 50)
[[0.856497   0.14350295]] 0 86.00000143051147
shape (50, 50)
[[0.9088927  0.09110733]] 0 91.00000262260437
shape (50, 50)
[[0.9363414  0.06365861]] 0 93.99999976158142
shape (50, 50)
[[0.95495754 0.04504241]] 0 94.9999988079071
shape (50, 50)
[[0.9544292  

[[0.712045   0.28795502]] 0 70.99999785423279
shape (50, 50)
[[0.8844862  0.11551381]] 0 87.99999952316284
shape (50, 50)
[[0.86986977 0.13013028]] 0 87.00000047683716
shape (50, 50)
[[0.68831396 0.3116861 ]] 0 68.99999976158142
shape (50, 50)
[[0.4338146  0.56618536]] 1 56.99999928474426
shape (50, 50)
[[0.43516728 0.56483275]] 1 56.00000023841858
shape (50, 50)
[[0.46945512 0.5305449 ]] 1 52.99999713897705
shape (50, 50)
[[0.09800296 0.9019971 ]] 1 89.99999761581421
shape (50, 50)
[[0.00823016 0.9917698 ]] 1 99.00000095367432
shape (50, 50)
[[0.00321345 0.9967866 ]] 1 100.0
shape (50, 50)
[[0.12363047 0.8763695 ]] 1 87.99999952316284
shape (50, 50)
[[0.13088629 0.8691137 ]] 1 87.00000047683716
shape (50, 50)
[[8.7260950e-04 9.9912745e-01]] 1 100.0
shape (50, 50)
[[1.5819514e-04 9.9984181e-01]] 1 100.0
shape (50, 50)
[[2.3018982e-04 9.9976987e-01]] 1 100.0
shape (50, 50)
[[0.00359733 0.9964026 ]] 1 100.0
shape (50, 50)
[[0.11199068 0.88800925]] 1 88.99999856948853
shape (50, 50)
[[0.9

[[0.7404944 0.2595057]] 0 74.00000095367432
shape (50, 50)
[[0.8296712  0.17032881]] 0 82.99999833106995
shape (50, 50)
[[0.8024258  0.19757426]] 0 80.0000011920929
shape (50, 50)
[[0.74462396 0.25537604]] 0 74.00000095367432
shape (50, 50)
[[0.7237281  0.27627185]] 0 72.00000286102295
shape (50, 50)
[[0.66352874 0.33647126]] 0 66.00000262260437
shape (50, 50)
[[0.7198561  0.28014392]] 0 72.00000286102295
shape (50, 50)
[[0.53601253 0.4639875 ]] 0 54.00000214576721
shape (50, 50)
[[0.5866033  0.41339663]] 0 58.99999737739563
shape (50, 50)
[[0.65990853 0.3400915 ]] 0 66.00000262260437
shape (50, 50)
[[0.58057487 0.41942507]] 0 57.999998331069946
shape (50, 50)
[[0.6633665 0.3366334]] 0 66.00000262260437
shape (50, 50)
[[0.5196576  0.48034245]] 0 51.99999809265137
shape (50, 50)
[[0.46139637 0.53860366]] 1 54.00000214576721
shape (50, 50)
[[0.32569438 0.6743057 ]] 1 67.00000166893005
shape (50, 50)
[[0.10965074 0.89034927]] 1 88.99999856948853
shape (50, 50)
[[0.06606094 0.93393904]] 1 

shape (50, 50)
[[0.96832573 0.03167427]] 0 97.00000286102295
shape (50, 50)
[[0.9616427  0.03835736]] 0 95.99999785423279
shape (50, 50)
[[0.9288996  0.07110037]] 0 93.00000071525574
shape (50, 50)
[[0.917282   0.08271796]] 0 92.00000166893005
shape (50, 50)
[[0.9476257  0.05237433]] 0 94.9999988079071
shape (50, 50)
[[0.97859174 0.02140829]] 0 98.00000190734863
shape (50, 50)
[[0.97325855 0.02674139]] 0 97.00000286102295
shape (50, 50)
[[0.9707267  0.02927326]] 0 97.00000286102295
shape (50, 50)
[[0.94767034 0.05232967]] 0 94.9999988079071
shape (50, 50)
[[0.79256606 0.20743388]] 0 79.00000214576721
shape (50, 50)
[[0.7588542  0.24114579]] 0 75.99999904632568
shape (50, 50)
[[0.77722067 0.2227793 ]] 0 77.99999713897705
shape (50, 50)
[[0.6906961  0.30930388]] 0 68.99999976158142
shape (50, 50)
[[0.5749533  0.42504668]] 0 56.99999928474426
shape (50, 50)
[[0.584952 0.415048]] 0 57.999998331069946
shape (50, 50)
[[0.49516246 0.5048375 ]] 1 50.0
shape (50, 50)
[[0.67967474 0.32032531]] 0

shape (50, 50)
[[0.40300474 0.5969953 ]] 1 60.00000238418579
shape (50, 50)
[[0.86557186 0.13442819]] 0 87.00000047683716
shape (50, 50)
[[0.6125549 0.3874451]] 0 61.000001430511475
shape (50, 50)
[[0.556122   0.44387797]] 0 56.00000023841858
shape (50, 50)
[[0.5853633 0.4146366]] 0 58.99999737739563
shape (50, 50)
[[0.78392446 0.21607552]] 0 77.99999713897705
shape (50, 50)
[[0.91465926 0.08534078]] 0 91.00000262260437
shape (50, 50)
[[0.77065337 0.22934663]] 0 76.99999809265137
shape (50, 50)
[[0.895997   0.10400296]] 0 89.99999761581421
shape (50, 50)
[[0.8586252  0.14137489]] 0 86.00000143051147
shape (50, 50)
[[0.84774673 0.15225331]] 0 85.00000238418579
shape (50, 50)
[[0.704793   0.29520705]] 0 69.9999988079071
shape (50, 50)
[[0.927949   0.07205104]] 0 93.00000071525574
shape (50, 50)
[[0.9636686  0.03633135]] 0 95.99999785423279
shape (50, 50)
[[0.81972575 0.18027425]] 0 81.99999928474426
shape (50, 50)
[[0.96914256 0.03085743]] 0 97.00000286102295
shape (50, 50)
[[0.9907569  

shape (50, 50)
[[0.99332523 0.0066748 ]] 0 99.00000095367432
shape (50, 50)
[[0.994117   0.00588302]] 0 99.00000095367432
shape (50, 50)
[[0.9888205  0.01117957]] 0 99.00000095367432
shape (50, 50)
[[0.9987658  0.00123422]] 0 100.0
shape (50, 50)
[[0.99840873 0.00159133]] 0 100.0
shape (50, 50)
[[0.9959663  0.00403365]] 0 100.0
shape (50, 50)
[[0.99642366 0.00357636]] 0 100.0
shape (50, 50)
[[0.9953727  0.00462725]] 0 100.0
shape (50, 50)
[[0.99269533 0.0073047 ]] 0 99.00000095367432
shape (50, 50)
[[0.9932922  0.00670781]] 0 99.00000095367432
shape (50, 50)
[[0.99363446 0.00636547]] 0 99.00000095367432
shape (50, 50)
[[0.98240143 0.01759862]] 0 98.00000190734863
shape (50, 50)
[[0.9784564  0.02154356]] 0 98.00000190734863
shape (50, 50)
[[0.99335045 0.00664958]] 0 99.00000095367432
shape (50, 50)
[[0.9936014  0.00639857]] 0 99.00000095367432
shape (50, 50)
[[0.9905855 0.0094145]] 0 99.00000095367432
shape (50, 50)
[[0.99110454 0.00889548]] 0 99.00000095367432
shape (50, 50)
[[0.987241

shape (50, 50)
[[0.6086793 0.3913207]] 0 61.000001430511475
shape (50, 50)
[[0.06947422 0.9305258 ]] 1 93.00000071525574
shape (50, 50)
[[0.17760105 0.822399  ]] 1 81.99999928474426
shape (50, 50)
[[0.4710956 0.5289043]] 1 52.99999713897705
shape (50, 50)
[[0.96126413 0.03873582]] 0 95.99999785423279
shape (50, 50)
[[0.54652965 0.4534704 ]] 0 55.000001192092896
shape (50, 50)
[[0.8598765  0.14012352]] 0 86.00000143051147
shape (50, 50)
[[9.9973351e-01 2.6647912e-04]] 0 100.0
shape (50, 50)
[[9.9999964e-01 3.6236270e-07]] 0 100.0
shape (50, 50)
[[9.9999976e-01 2.1064150e-07]] 0 100.0
shape (50, 50)
[[0.69469887 0.30530116]] 0 68.99999976158142
shape (50, 50)
[[0.9461127  0.05388731]] 0 94.9999988079071
shape (50, 50)
[[9.9999976e-01 2.0590257e-07]] 0 100.0
shape (50, 50)
[[9.999999e-01 7.572349e-08]] 0 100.0
shape (50, 50)
[[9.9999940e-01 5.9896274e-07]] 0 100.0
shape (50, 50)
[[9.9999917e-01 8.1232764e-07]] 0 100.0
shape (50, 50)
[[9.9999964e-01 3.5831289e-07]] 0 100.0
shape (50, 50)
[

shape (50, 50)
[[0.9795045  0.02049544]] 0 98.00000190734863
shape (50, 50)
[[0.9749987  0.02500129]] 0 97.00000286102295
shape (50, 50)
[[0.9450793  0.05492072]] 0 94.9999988079071
shape (50, 50)
[[0.88329256 0.11670741]] 0 87.99999952316284
shape (50, 50)
[[0.85920376 0.14079629]] 0 86.00000143051147
shape (50, 50)
[[0.75223845 0.24776159]] 0 75.0
shape (50, 50)
[[0.7973105 0.2026895]] 0 80.0000011920929
shape (50, 50)
[[0.77036685 0.22963308]] 0 76.99999809265137
shape (50, 50)
[[0.9066801  0.09331989]] 0 91.00000262260437
shape (50, 50)
[[0.87910235 0.1208977 ]] 0 87.99999952316284
shape (50, 50)
[[0.75771207 0.24228795]] 0 75.99999904632568
shape (50, 50)
[[0.7724395  0.22756052]] 0 76.99999809265137
shape (50, 50)
[[0.74343413 0.2565659 ]] 0 74.00000095367432
shape (50, 50)
[[0.62518936 0.37481064]] 0 62.99999952316284
shape (50, 50)
[[0.6828849  0.31711513]] 0 68.00000071525574
shape (50, 50)
[[0.7853551  0.21464491]] 0 79.00000214576721
shape (50, 50)
[[0.6732654  0.32673466]] 

[[0.98708713 0.01291287]] 0 99.00000095367432
shape (50, 50)
[[0.9884675  0.01153246]] 0 99.00000095367432
shape (50, 50)
[[0.99209833 0.0079017 ]] 0 99.00000095367432
shape (50, 50)
[[0.98290575 0.01709428]] 0 98.00000190734863
shape (50, 50)
[[0.970948   0.02905208]] 0 97.00000286102295
shape (50, 50)
[[0.97655845 0.02344152]] 0 98.00000190734863
shape (50, 50)
[[0.99526113 0.00473888]] 0 100.0
shape (50, 50)
[[0.97890764 0.02109237]] 0 98.00000190734863
shape (50, 50)
[[0.99140066 0.00859936]] 0 99.00000095367432
shape (50, 50)
[[0.9932597  0.00674026]] 0 99.00000095367432
shape (50, 50)
[[0.9945745  0.00542551]] 0 99.00000095367432
shape (50, 50)
[[0.9849474  0.01505254]] 0 98.00000190734863
shape (50, 50)
[[0.9848828  0.01511723]] 0 98.00000190734863
shape (50, 50)
[[0.9854629  0.01453711]] 0 99.00000095367432
shape (50, 50)
[[0.982228   0.01777198]] 0 98.00000190734863
shape (50, 50)
[[0.9660763  0.03392371]] 0 97.00000286102295
shape (50, 50)
[[0.9583461  0.04165383]] 0 95.99999

shape (50, 50)
[[0.8381167  0.16188325]] 0 83.99999737739563
shape (50, 50)
[[0.9085273  0.09147265]] 0 91.00000262260437
shape (50, 50)
[[0.93805474 0.06194528]] 0 93.99999976158142
shape (50, 50)
[[0.8869996  0.11300043]] 0 88.99999856948853
shape (50, 50)
[[0.88785285 0.11214716]] 0 88.99999856948853
shape (50, 50)
[[0.85719615 0.14280383]] 0 86.00000143051147
shape (50, 50)
[[0.8822443  0.11775575]] 0 87.99999952316284
shape (50, 50)
[[0.91239035 0.08760964]] 0 91.00000262260437
shape (50, 50)
[[0.960476 0.039524]] 0 95.99999785423279
shape (50, 50)
[[0.9510673  0.04893262]] 0 94.9999988079071
shape (50, 50)
[[0.96230453 0.03769545]] 0 95.99999785423279
shape (50, 50)
[[0.9688492 0.0311509]] 0 97.00000286102295
shape (50, 50)
[[0.96656245 0.03343754]] 0 97.00000286102295
shape (50, 50)
[[0.9563365  0.04366354]] 0 95.99999785423279
shape (50, 50)
[[0.9567968  0.04320316]] 0 95.99999785423279
shape (50, 50)
[[0.9710959  0.02890414]] 0 97.00000286102295
shape (50, 50)
[[0.9714531  0.0

shape (50, 50)
[[9.9999964e-01 3.0803517e-07]] 0 100.0
shape (50, 50)
[[9.9999940e-01 5.5139367e-07]] 0 100.0
shape (50, 50)
[[9.999994e-01 5.466182e-07]] 0 100.0
shape (50, 50)
[[1.0000000e+00 2.7132772e-08]] 0 100.0
shape (50, 50)
[[1.0000000e+00 5.3075993e-08]] 0 100.0
shape (50, 50)
[[9.9999988e-01 8.1086036e-08]] 0 100.0
shape (50, 50)
[[9.9999988e-01 1.1376324e-07]] 0 100.0
shape (50, 50)
[[9.9999976e-01 2.8599010e-07]] 0 100.0
shape (50, 50)
[[9.9999964e-01 3.5149847e-07]] 0 100.0
shape (50, 50)
[[9.999993e-01 7.443782e-07]] 0 100.0
shape (50, 50)
[[9.9999976e-01 2.0811977e-07]] 0 100.0
shape (50, 50)
[[9.9999964e-01 3.6246914e-07]] 0 100.0
shape (50, 50)
[[9.9999976e-01 1.9879525e-07]] 0 100.0
shape (50, 50)
[[9.9999976e-01 2.3623645e-07]] 0 100.0
shape (50, 50)
[[9.999999e-01 6.745593e-08]] 0 100.0
shape (50, 50)
[[1.000000e+00 4.365529e-08]] 0 100.0
shape (50, 50)
[[9.999999e-01 7.932379e-08]] 0 100.0
shape (50, 50)
[[9.999999e-01 7.311456e-08]] 0 100.0
shape (50, 50)
[[9.999

shape (50, 50)
[[2.0362840e-04 9.9979633e-01]] 1 100.0
shape (50, 50)
[[2.2168043e-04 9.9977833e-01]] 1 100.0
shape (50, 50)
[[2.3444365e-04 9.9976557e-01]] 1 100.0
shape (50, 50)
[[1.8924243e-04 9.9981076e-01]] 1 100.0
shape (50, 50)
[[2.6041822e-04 9.9973959e-01]] 1 100.0
shape (50, 50)
[[3.4661853e-04 9.9965334e-01]] 1 100.0
shape (50, 50)
[[4.1523558e-04 9.9958473e-01]] 1 100.0
shape (50, 50)
[[3.2197268e-04 9.9967802e-01]] 1 100.0
shape (50, 50)
[[3.7055253e-04 9.9962938e-01]] 1 100.0
shape (50, 50)
[[6.5228634e-04 9.9934775e-01]] 1 100.0
shape (50, 50)
[[0.01177506 0.988225  ]] 1 99.00000095367432
shape (50, 50)
[[9.9999046e-01 9.5741289e-06]] 0 100.0
shape (50, 50)
[[1.000000e+00 2.571069e-13]] 0 100.0
shape (50, 50)
[[1.0000000e+00 1.8865432e-12]] 0 100.0
shape (50, 50)
[[1.0000000e+00 6.9745112e-12]] 0 100.0
shape (50, 50)
[[1.0000000e+00 1.8083478e-10]] 0 100.0
shape (50, 50)
[[9.9999976e-01 2.2251700e-07]] 0 100.0
shape (50, 50)
[[9.9999881e-01 1.2154596e-06]] 0 100.0
shape 

[[0.5353631  0.46463695]] 0 54.00000214576721
shape (50, 50)
[[0.4091444  0.59085554]] 1 58.99999737739563
shape (50, 50)
[[0.47935638 0.52064365]] 1 51.99999809265137
shape (50, 50)
[[0.5570383  0.44296172]] 0 56.00000023841858
shape (50, 50)
[[0.5272753  0.47272465]] 0 52.99999713897705
shape (50, 50)
[[0.46597624 0.5340237 ]] 1 52.99999713897705
shape (50, 50)
[[0.7352125  0.26478744]] 0 74.00000095367432
shape (50, 50)
[[0.63852054 0.36147946]] 0 63.999998569488525
shape (50, 50)
[[0.800211   0.19978903]] 0 80.0000011920929
shape (50, 50)
[[0.7840622  0.21593778]] 0 77.99999713897705
shape (50, 50)
[[0.82117796 0.178822  ]] 0 81.99999928474426
shape (50, 50)
[[0.8614634  0.13853657]] 0 86.00000143051147
shape (50, 50)
[[0.8231858  0.17681426]] 0 81.99999928474426
shape (50, 50)
[[0.7164198  0.28358018]] 0 72.00000286102295
shape (50, 50)
[[0.88809687 0.11190315]] 0 88.99999856948853
shape (50, 50)
[[0.7462667  0.25373328]] 0 75.0
shape (50, 50)
[[0.6031064 0.3968936]] 0 60.00000238

shape (50, 50)
[[1.5606043e-05 9.9998438e-01]] 1 100.0
shape (50, 50)
[[2.8796005e-05 9.9997115e-01]] 1 100.0
shape (50, 50)
[[2.2175735e-05 9.9997783e-01]] 1 100.0
shape (50, 50)
[[1.9005562e-05 9.9998105e-01]] 1 100.0
shape (50, 50)
[[2.1534526e-05 9.9997842e-01]] 1 100.0
shape (50, 50)
[[3.1887885e-05 9.9996805e-01]] 1 100.0
shape (50, 50)
[[3.648508e-05 9.999635e-01]] 1 100.0
shape (50, 50)
[[5.3602442e-05 9.9994636e-01]] 1 100.0
shape (50, 50)
[[1.0340694e-04 9.9989653e-01]] 1 100.0
shape (50, 50)
[[1.2548076e-04 9.9987447e-01]] 1 100.0
shape (50, 50)
[[1.0257492e-04 9.9989736e-01]] 1 100.0
shape (50, 50)
[[1.1111565e-04 9.9988890e-01]] 1 100.0
shape (50, 50)
[[1.01291975e-04 9.99898672e-01]] 1 100.0
shape (50, 50)
[[1.2732804e-04 9.9987268e-01]] 1 100.0
shape (50, 50)
[[1.2354468e-04 9.9987650e-01]] 1 100.0
shape (50, 50)
[[1.3294024e-04 9.9986708e-01]] 1 100.0
shape (50, 50)
[[1.3695406e-04 9.9986303e-01]] 1 100.0
shape (50, 50)
[[1.2983991e-04 9.9987018e-01]] 1 100.0
shape (50,

[[0.99502265 0.00497736]] 0 100.0
shape (50, 50)
[[0.9968761  0.00312381]] 0 100.0
shape (50, 50)
[[0.99420387 0.00579613]] 0 99.00000095367432
shape (50, 50)
[[0.98732996 0.01267003]] 0 99.00000095367432
shape (50, 50)
[[0.9951174  0.00488255]] 0 100.0
shape (50, 50)
[[0.99162227 0.00837773]] 0 99.00000095367432
shape (50, 50)
[[0.99545336 0.00454662]] 0 100.0
shape (50, 50)
[[0.9948926  0.00510741]] 0 99.00000095367432
shape (50, 50)
[[0.9947464  0.00525357]] 0 99.00000095367432
shape (50, 50)
[[0.9941093  0.00589074]] 0 99.00000095367432
shape (50, 50)
[[0.9956245 0.0043756]] 0 100.0
shape (50, 50)
[[0.9976119  0.00238807]] 0 100.0
shape (50, 50)
[[0.996585   0.00341494]] 0 100.0
shape (50, 50)
[[0.99437934 0.00562064]] 0 99.00000095367432
shape (50, 50)
[[0.9951521  0.00484783]] 0 100.0
shape (50, 50)
[[0.9922356  0.00776436]] 0 99.00000095367432
shape (50, 50)
[[0.9909258  0.00907423]] 0 99.00000095367432
shape (50, 50)
[[9.9992371e-01 7.6238815e-05]] 0 100.0
shape (50, 50)
[[9.99

shape (50, 50)
[[0.6096612  0.39033878]] 0 61.000001430511475
shape (50, 50)
[[0.9352575  0.06474248]] 0 93.99999976158142
shape (50, 50)
[[0.13095875 0.8690412 ]] 1 87.00000047683716
shape (50, 50)
[[4.7582237e-04 9.9952424e-01]] 1 100.0
shape (50, 50)
[[1.8057521e-04 9.9981946e-01]] 1 100.0
shape (50, 50)
[[1.1382373e-04 9.9988616e-01]] 1 100.0
shape (50, 50)
[[1.10683126e-04 9.99889255e-01]] 1 100.0
shape (50, 50)
[[1.1383654e-04 9.9988616e-01]] 1 100.0
shape (50, 50)
[[1.1254200e-04 9.9988747e-01]] 1 100.0
shape (50, 50)
[[9.6877506e-05 9.9990308e-01]] 1 100.0
shape (50, 50)
[[8.861021e-05 9.999114e-01]] 1 100.0
shape (50, 50)
[[8.8554625e-05 9.9991143e-01]] 1 100.0
shape (50, 50)
[[8.8447785e-05 9.9991155e-01]] 1 100.0
shape (50, 50)
[[8.8488363e-05 9.9991155e-01]] 1 100.0
shape (50, 50)
[[8.9023859e-05 9.9991095e-01]] 1 100.0
shape (50, 50)
[[8.872122e-05 9.999113e-01]] 1 100.0
shape (50, 50)
[[8.8806635e-05 9.9991119e-01]] 1 100.0
shape (50, 50)
[[8.882425e-05 9.999112e-01]] 1 1

shape (50, 50)
[[8.9126639e-05 9.9991083e-01]] 1 100.0
shape (50, 50)
[[8.8851695e-05 9.9991119e-01]] 1 100.0
shape (50, 50)
[[8.8412031e-05 9.9991155e-01]] 1 100.0
shape (50, 50)
[[8.9124260e-05 9.9991083e-01]] 1 100.0
shape (50, 50)
[[8.8917805e-05 9.9991107e-01]] 1 100.0
shape (50, 50)
[[8.863750e-05 9.999113e-01]] 1 100.0
shape (50, 50)
[[8.8402412e-05 9.9991155e-01]] 1 100.0
shape (50, 50)
[[8.885687e-05 9.999112e-01]] 1 100.0
shape (50, 50)
[[8.8369976e-05 9.9991167e-01]] 1 100.0
shape (50, 50)
[[8.865179e-05 9.999113e-01]] 1 100.0
shape (50, 50)
[[8.9605222e-05 9.9991035e-01]] 1 100.0
shape (50, 50)
[[8.940874e-05 9.999106e-01]] 1 100.0
shape (50, 50)
[[8.9131740e-05 9.9991083e-01]] 1 100.0
shape (50, 50)
[[8.9129528e-05 9.9991083e-01]] 1 100.0
shape (50, 50)
[[8.867225e-05 9.999113e-01]] 1 100.0
shape (50, 50)
[[8.8912719e-05 9.9991107e-01]] 1 100.0
shape (50, 50)
[[8.8928151e-05 9.9991107e-01]] 1 100.0
shape (50, 50)
[[8.9233785e-05 9.9991071e-01]] 1 100.0
shape (50, 50)
[[8.8

[[8.866312e-05 9.999113e-01]] 1 100.0
shape (50, 50)
[[8.8602435e-05 9.9991143e-01]] 1 100.0
shape (50, 50)
[[8.9024281e-05 9.9991095e-01]] 1 100.0
shape (50, 50)
[[8.8398876e-05 9.9991155e-01]] 1 100.0
shape (50, 50)
[[8.8456647e-05 9.9991155e-01]] 1 100.0
shape (50, 50)
[[8.926408e-05 9.999107e-01]] 1 100.0
shape (50, 50)
[[8.8428977e-05 9.9991155e-01]] 1 100.0
shape (50, 50)
[[8.8988294e-05 9.9991095e-01]] 1 100.0
shape (50, 50)
[[8.8976507e-05 9.9991107e-01]] 1 100.0
shape (50, 50)
[[8.855328e-05 9.999114e-01]] 1 100.0
shape (50, 50)
[[8.881586e-05 9.999112e-01]] 1 100.0
shape (50, 50)
[[8.9040244e-05 9.9991095e-01]] 1 100.0
shape (50, 50)
[[8.9205809e-05 9.9991083e-01]] 1 100.0
shape (50, 50)
[[8.9008921e-05 9.9991095e-01]] 1 100.0
shape (50, 50)
[[8.8920351e-05 9.9991107e-01]] 1 100.0
shape (50, 50)
[[8.876310e-05 9.999112e-01]] 1 100.0
shape (50, 50)
[[8.8493936e-05 9.9991155e-01]] 1 100.0
shape (50, 50)
[[8.9161746e-05 9.9991083e-01]] 1 100.0
shape (50, 50)
[[8.8908819e-05 9.99

[[1.0000000e+00 1.6519434e-09]] 0 100.0
shape (50, 50)
[[1.0000000e+00 3.2309522e-08]] 0 100.0
shape (50, 50)
[[0.02867991 0.9713201 ]] 1 97.00000286102295
shape (50, 50)
[[0.08369841 0.91630155]] 1 92.00000166893005
shape (50, 50)
[[0.00268596 0.99731404]] 1 100.0
shape (50, 50)
[[8.4905187e-04 9.9915099e-01]] 1 100.0
shape (50, 50)
[[0.0032146 0.9967854]] 1 100.0
shape (50, 50)
[[0.00129461 0.9987054 ]] 1 100.0
shape (50, 50)
[[0.00219638 0.9978036 ]] 1 100.0
shape (50, 50)
[[0.40112278 0.5988772 ]] 1 60.00000238418579
shape (50, 50)
[[0.41608498 0.58391505]] 1 57.999998331069946
shape (50, 50)
[[0.56508327 0.43491676]] 0 56.99999928474426
shape (50, 50)
[[0.8113094 0.1886906]] 0 81.00000023841858
shape (50, 50)
[[0.4917205  0.50827956]] 1 50.999999046325684
shape (50, 50)
[[0.17634378 0.82365626]] 1 81.99999928474426
shape (50, 50)
[[0.05437568 0.94562435]] 1 94.9999988079071
shape (50, 50)
[[0.09873834 0.9012616 ]] 1 89.99999761581421
shape (50, 50)
[[0.5551017  0.44489828]] 0 56.0

[[6.685504e-05 9.999331e-01]] 1 100.0
shape (50, 50)
[[0.01831906 0.9816809 ]] 1 98.00000190734863
shape (50, 50)
[[0.21117857 0.78882146]] 1 79.00000214576721
shape (50, 50)
[[1.4436854e-05 9.9998558e-01]] 1 100.0
shape (50, 50)
[[8.677810e-06 9.999913e-01]] 1 100.0
shape (50, 50)
[[6.8165477e-06 9.9999321e-01]] 1 100.0
shape (50, 50)
[[1.3857207e-05 9.9998617e-01]] 1 100.0
shape (50, 50)
[[2.7704795e-05 9.9997234e-01]] 1 100.0
shape (50, 50)
[[1.5649691e-04 9.9984348e-01]] 1 100.0
shape (50, 50)
[[0.01760405 0.9823959 ]] 1 98.00000190734863
shape (50, 50)
[[0.18317688 0.8168232 ]] 1 81.99999928474426
shape (50, 50)
[[0.07930172 0.9206983 ]] 1 92.00000166893005
shape (50, 50)
[[0.18030606 0.819694  ]] 1 81.99999928474426
shape (50, 50)
[[0.19314091 0.8068591 ]] 1 81.00000023841858
shape (50, 50)
[[0.06321377 0.93678623]] 1 93.99999976158142
shape (50, 50)
[[0.46017066 0.53982925]] 1 54.00000214576721
shape (50, 50)
[[0.48983082 0.5101692 ]] 1 50.999999046325684
shape (50, 50)
[[0.4202

error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:730: error: (-215:Assertion failed) !buf.empty() in function 'cv::imdecode_'
